# Generated by Django 3.0.7 on 2020-06-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('cod_prod', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('mark', models.CharField(max_length=70)),
                ('type_p', models.CharField(max_length=70)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('size', models.CharField(max_length=30)),
            ],
        ),
    ]
